require("dotenv").config();
const mongoose = require("mongoose");
const Vocabulary = require("../models/Vocabulary.model");
const User = require("../models/User.model");

const seedData = [
  // ---------- HSK 1 (FULL 150 WORDS) ----------
  {
    chinese: "爱",
    pinyin: "ài",
    vietnamese: "yêu",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "八",
    pinyin: "bā",
    vietnamese: "tám",
    level: "HSK1",
    wordType: "number",
  },
  {
    chinese: "爸爸",
    pinyin: "bàba",
    vietnamese: "bố",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "杯子",
    pinyin: "bēizi",
    vietnamese: "cốc",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "北京",
    pinyin: "běijīng",
    vietnamese: "Bắc Kinh",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "本",
    pinyin: "běn",
    vietnamese: "quyển (lượng từ)",
    level: "HSK1",
    wordType: "measure",
  },
  {
    chinese: "不",
    pinyin: "bù",
    vietnamese: "không",
    level: "HSK1",
    wordType: "adverb",
  },
  {
    chinese: "菜",
    pinyin: "cài",
    vietnamese: "món ăn",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "茶",
    pinyin: "chá",
    vietnamese: "trà",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "吃",
    pinyin: "chī",
    vietnamese: "ăn",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "出租车",
    pinyin: "chūzūchē",
    vietnamese: "taxi",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "打电话",
    pinyin: "dǎ diànhuà",
    vietnamese: "gọi điện thoại",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "大",
    pinyin: "dà",
    vietnamese: "to / lớn",
    level: "HSK1",
    wordType: "adjective",
  },
  {
    chinese: "点",
    pinyin: "diǎn",
    vietnamese: "giờ",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "电脑",
    pinyin: "diànnǎo",
    vietnamese: "máy tính",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "电视",
    pinyin: "diànshì",
    vietnamese: "tivi",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "电影",
    pinyin: "diànyǐng",
    vietnamese: "phim",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "东西",
    pinyin: "dōngxi",
    vietnamese: "đồ vật",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "都",
    pinyin: "dōu",
    vietnamese: "đều",
    level: "HSK1",
    wordType: "adverb",
  },
  {
    chinese: "读",
    pinyin: "dú",
    vietnamese: "đọc",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "多",
    pinyin: "duō",
    vietnamese: "nhiều",
    level: "HSK1",
    wordType: "adjective",
  },

  {
    chinese: "儿子",
    pinyin: "érzi",
    vietnamese: "con trai",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "二",
    pinyin: "èr",
    vietnamese: "hai",
    level: "HSK1",
    wordType: "number",
  },
  {
    chinese: "饭店",
    pinyin: "fàndiàn",
    vietnamese: "nhà hàng",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "飞机",
    pinyin: "fēijī",
    vietnamese: "máy bay",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "分钟",
    pinyin: "fēnzhōng",
    vietnamese: "phút",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "高兴",
    pinyin: "gāoxìng",
    vietnamese: "vui",
    level: "HSK1",
    wordType: "adjective",
  },
  {
    chinese: "个",
    pinyin: "gè",
    vietnamese: "cái (lượng từ)",
    level: "HSK1",
    wordType: "measure",
  },
  {
    chinese: "工作",
    pinyin: "gōngzuò",
    vietnamese: "công việc / làm việc",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "狗",
    pinyin: "gǒu",
    vietnamese: "chó",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "汉语",
    pinyin: "hànyǔ",
    vietnamese: "tiếng Trung",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "好吃",
    pinyin: "hǎochī",
    vietnamese: "ngon",
    level: "HSK1",
    wordType: "adjective",
  },
  {
    chinese: "喝",
    pinyin: "hē",
    vietnamese: "uống",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "和",
    pinyin: "hé",
    vietnamese: "và",
    level: "HSK1",
    wordType: "conjunction",
  },
  {
    chinese: "很",
    pinyin: "hěn",
    vietnamese: "rất",
    level: "HSK1",
    wordType: "adverb",
  },
  {
    chinese: "后面",
    pinyin: "hòumiàn",
    vietnamese: "đằng sau",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "回",
    pinyin: "huí",
    vietnamese: "trở về",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "会",
    pinyin: "huì",
    vietnamese: "biết / có thể",
    level: "HSK1",
    wordType: "verb",
  },

  {
    chinese: "家",
    pinyin: "jiā",
    vietnamese: "nhà",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "叫",
    pinyin: "jiào",
    vietnamese: "gọi / tên là",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "今天",
    pinyin: "jīntiān",
    vietnamese: "hôm nay",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "九",
    pinyin: "jiǔ",
    vietnamese: "chín",
    level: "HSK1",
    wordType: "number",
  },
  {
    chinese: "开",
    pinyin: "kāi",
    vietnamese: "mở",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "看",
    pinyin: "kàn",
    vietnamese: "xem / nhìn",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "看见",
    pinyin: "kànjiàn",
    vietnamese: "nhìn thấy",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "块",
    pinyin: "kuài",
    vietnamese: "tệ (tiền)",
    level: "HSK1",
    wordType: "measure",
  },
  {
    chinese: "来",
    pinyin: "lái",
    vietnamese: "đến",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "老师",
    pinyin: "lǎoshī",
    vietnamese: "giáo viên",
    level: "HSK1",
    wordType: "noun",
  },

  {
    chinese: "冷",
    pinyin: "lěng",
    vietnamese: "lạnh",
    level: "HSK1",
    wordType: "adjective",
  },
  {
    chinese: "里",
    pinyin: "lǐ",
    vietnamese: "bên trong",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "六",
    pinyin: "liù",
    vietnamese: "sáu",
    level: "HSK1",
    wordType: "number",
  },
  {
    chinese: "妈妈",
    pinyin: "māma",
    vietnamese: "mẹ",
    level: "HSK1",
    wordType: "noun",
  },

  {
    chinese: "买",
    pinyin: "mǎi",
    vietnamese: "mua",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "猫",
    pinyin: "māo",
    vietnamese: "mèo",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "没",
    pinyin: "méi",
    vietnamese: "không có",
    level: "HSK1",
    wordType: "adverb",
  },
  {
    chinese: "米饭",
    pinyin: "mǐfàn",
    vietnamese: "cơm",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "明天",
    pinyin: "míngtiān",
    vietnamese: "ngày mai",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "名字",
    pinyin: "míngzi",
    vietnamese: "tên",
    level: "HSK1",
    wordType: "noun",
  },

  {
    chinese: "那",
    pinyin: "nà",
    vietnamese: "kia / đó",
    level: "HSK1",
    wordType: "pronoun",
  },

  {
    chinese: "能",
    pinyin: "néng",
    vietnamese: "có thể",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "你",
    pinyin: "nǐ",
    vietnamese: "bạn",
    level: "HSK1",
    wordType: "pronoun",
  },
  {
    chinese: "年",
    pinyin: "nián",
    vietnamese: "năm",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "女儿",
    pinyin: "nǚ'ér",
    vietnamese: "con gái",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "朋友",
    pinyin: "péngyou",
    vietnamese: "bạn bè",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "漂亮",
    pinyin: "piàoliang",
    vietnamese: "đẹp",
    level: "HSK1",
    wordType: "adjective",
  },
  {
    chinese: "苹果",
    pinyin: "píngguǒ",
    vietnamese: "táo",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "七",
    pinyin: "qī",
    vietnamese: "bảy",
    level: "HSK1",
    wordType: "number",
  },
  {
    chinese: "钱",
    pinyin: "qián",
    vietnamese: "tiền",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "前面",
    pinyin: "qiánmiàn",
    vietnamese: "phía trước",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "请",
    pinyin: "qǐng",
    vietnamese: "mời / xin vui lòng",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "去",
    pinyin: "qù",
    vietnamese: "đi",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "热",
    pinyin: "rè",
    vietnamese: "nóng",
    level: "HSK1",
    wordType: "adjective",
  },
  {
    chinese: "人",
    pinyin: "rén",
    vietnamese: "người",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "认识",
    pinyin: "rènshi",
    vietnamese: "biết / quen",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "三",
    pinyin: "sān",
    vietnamese: "ba",
    level: "HSK1",
    wordType: "number",
  },
  {
    chinese: "商店",
    pinyin: "shāngdiàn",
    vietnamese: "cửa hàng",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "上",
    pinyin: "shàng",
    vietnamese: "lên / trên",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "少",
    pinyin: "shǎo",
    vietnamese: "ít",
    level: "HSK1",
    wordType: "adjective",
  },

  {
    chinese: "十",
    pinyin: "shí",
    vietnamese: "mười",
    level: "HSK1",
    wordType: "number",
  },
  {
    chinese: "时候",
    pinyin: "shíhou",
    vietnamese: "khi nào / lúc",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "是",
    pinyin: "shì",
    vietnamese: "là",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "书",
    pinyin: "shū",
    vietnamese: "sách",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "水",
    pinyin: "shuǐ",
    vietnamese: "nước",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "水果",
    pinyin: "shuǐguǒ",
    vietnamese: "trái cây",
    level: "HSK1",
    wordType: "noun",
  },
  {
    chinese: "睡觉",
    pinyin: "shuìjiào",
    vietnamese: "ngủ",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "说",
    pinyin: "shuō",
    vietnamese: "nói",
    level: "HSK1",
    wordType: "verb",
  },
  {
    chinese: "四",
    pinyin: "sì",
    vietnamese: "bốn",
    level: "HSK1",
    wordType: "number",
  },
  {
    chinese: "岁",
    pinyin: "suì",
    vietnamese: "tuổi",
    level: "HSK1",
    wordType: "measure",
  },
  {
    chinese: "他",
    pinyin: "tā",
    vietnamese: "anh ấy",
    level: "HSK1",
    wordType: "pronoun",
  },

  {
    chinese: "白",
    pinyin: "bái",
    vietnamese: "màu trắng",
    level: "HSK2",
    wordType: "adjective",
  },
  {
    chinese: "百",
    pinyin: "bǎi",
    vietnamese: "một trăm",
    level: "HSK2",
    wordType: "number",
  },
  {
    chinese: "帮助",
    pinyin: "bāngzhù",
    vietnamese: "giúp đỡ",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "报纸",
    pinyin: "bàozhǐ",
    vietnamese: "báo chí",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "比",
    pinyin: "bǐ",
    vietnamese: "so với",
    level: "HSK2",
    wordType: "preposition",
  },
  {
    chinese: "别",
    pinyin: "bié",
    vietnamese: "đừng",
    level: "HSK2",
    wordType: "adverb",
  },
  {
    chinese: "宾馆",
    pinyin: "bīnguǎn",
    vietnamese: "khách sạn",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "长",
    pinyin: "cháng",
    vietnamese: "dài",
    level: "HSK2",
    wordType: "adjective",
  },
  {
    chinese: "出",
    pinyin: "chū",
    vietnamese: "ra ngoài",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "穿",
    pinyin: "chuān",
    vietnamese: "mặc (quần áo)",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "次",
    pinyin: "cì",
    vietnamese: "lần (lượng từ)",
    level: "HSK2",
    wordType: "measure",
  },
  {
    chinese: "从",
    pinyin: "cóng",
    vietnamese: "từ (địa điểm)",
    level: "HSK2",
    wordType: "preposition",
  },
  {
    chinese: "错",
    pinyin: "cuò",
    vietnamese: "sai",
    level: "HSK2",
    wordType: "adjective",
  },
  {
    chinese: "打篮球",
    pinyin: "dǎ lánqiú",
    vietnamese: "chơi bóng rổ",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "大家",
    pinyin: "dàjiā",
    vietnamese: "mọi người",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "到",
    pinyin: "dào",
    vietnamese: "đến",
    level: "HSK2",
    wordType: "verb",
  },

  {
    chinese: "等",
    pinyin: "děng",
    vietnamese: "đợi",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "弟弟",
    pinyin: "dìdi",
    vietnamese: "em trai",
    level: "HSK2",
    wordType: "noun",
  },

  {
    chinese: "懂",
    pinyin: "dǒng",
    vietnamese: "hiểu",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "对",
    pinyin: "duì",
    vietnamese: "đúng",
    level: "HSK2",
    wordType: "adjective",
  },
  {
    chinese: "对于",
    pinyin: "duìyú",
    vietnamese: "đối với",
    level: "HSK2",
    wordType: "preposition",
  },
  {
    chinese: "房间",
    pinyin: "fángjiān",
    vietnamese: "phòng",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "非常",
    pinyin: "fēicháng",
    vietnamese: "rất / vô cùng",
    level: "HSK2",
    wordType: "adverb",
  },
  {
    chinese: "服务员",
    pinyin: "fúwùyuán",
    vietnamese: "nhân viên phục vụ",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "高",
    pinyin: "gāo",
    vietnamese: "cao",
    level: "HSK2",
    wordType: "adjective",
  },
  {
    chinese: "告诉",
    pinyin: "gàosu",
    vietnamese: "nói cho biết",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "哥哥",
    pinyin: "gēge",
    vietnamese: "anh trai",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "给",
    pinyin: "gěi",
    vietnamese: "cho, đưa",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "共",
    pinyin: "gòng",
    vietnamese: "tổng cộng",
    level: "HSK2",
    wordType: "adverb",
  },
  {
    chinese: "公交车",
    pinyin: "gōngjiāochē",
    vietnamese: "xe buýt",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "公司",
    pinyin: "gōngsī",
    vietnamese: "công ty",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "贵",
    pinyin: "guì",
    vietnamese: "đắt",
    level: "HSK2",
    wordType: "adjective",
  },

  {
    chinese: "还",
    pinyin: "hái",
    vietnamese: "vẫn còn / vẫn",
    level: "HSK2",
    wordType: "adverb",
  },
  {
    chinese: "孩子",
    pinyin: "háizi",
    vietnamese: "trẻ con",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "好吃",
    pinyin: "hǎochī",
    vietnamese: "ngon",
    level: "HSK2",
    wordType: "adjective",
  },
  {
    chinese: "黑",
    pinyin: "hēi",
    vietnamese: "màu đen",
    level: "HSK2",
    wordType: "adjective",
  },
  {
    chinese: "红",
    pinyin: "hóng",
    vietnamese: "màu đỏ",
    level: "HSK2",
    wordType: "adjective",
  },
  {
    chinese: "火车站",
    pinyin: "huǒchēzhàn",
    vietnamese: "ga tàu hỏa",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "机场",
    pinyin: "jīchǎng",
    vietnamese: "sân bay",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "鸡蛋",
    pinyin: "jīdàn",
    vietnamese: "trứng gà",
    level: "HSK2",
    wordType: "noun",
  },
  {
    chinese: "几乎",
    pinyin: "jīhū",
    vietnamese: "hầu như",
    level: "HSK2",
    wordType: "adverb",
  },
  {
    chinese: "记得",
    pinyin: "jìde",
    vietnamese: "nhớ",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "件",
    pinyin: "jiàn",
    vietnamese: "cái (lượng từ)",
    level: "HSK2",
    wordType: "measure",
  },
  {
    chinese: "教",
    pinyin: "jiāo",
    vietnamese: "dạy",
    level: "HSK2",
    wordType: "verb",
  },
  {
    chinese: "介绍",
    pinyin: "jièshào",
    vietnamese: "giới thiệu",
    level: "HSK2",
    wordType: "verb",
  },
  // ---------- HSK 3 (100 từ core) ----------
  {
    chinese: "安静",
    pinyin: "ānjìng",
    vietnamese: "yên tĩnh",
    level: "HSK3",
    wordType: "adjective",
  },

  {
    chinese: "班",
    pinyin: "bān",
    vietnamese: "lớp học",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "搬",
    pinyin: "bān",
    vietnamese: "dọn, chuyển",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "半",
    pinyin: "bàn",
    vietnamese: "một nửa",
    level: "HSK3",
    wordType: "number",
  },
  {
    chinese: "帮忙",
    pinyin: "bāngmáng",
    vietnamese: "giúp đỡ",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "包",
    pinyin: "bāo",
    vietnamese: "túi, bao",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "饱",
    pinyin: "bǎo",
    vietnamese: "no (ăn no)",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "北方",
    pinyin: "běifāng",
    vietnamese: "phía Bắc",
    level: "HSK3",
    wordType: "noun",
  },

  {
    chinese: "鼻子",
    pinyin: "bízi",
    vietnamese: "cái mũi",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "比较",
    pinyin: "bǐjiào",
    vietnamese: "tương đối",
    level: "HSK3",
    wordType: "adverb",
  },
  {
    chinese: "比赛",
    pinyin: "bǐsài",
    vietnamese: "thi đấu",
    level: "HSK3",
    wordType: "verb",
  },

  {
    chinese: "变化",
    pinyin: "biànhuà",
    vietnamese: "thay đổi",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "别人",
    pinyin: "biéren",
    vietnamese: "người khác",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "冰箱",
    pinyin: "bīngxiāng",
    vietnamese: "tủ lạnh",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "才",
    pinyin: "cái",
    vietnamese: "mới (chỉ thời gian chậm)",
    level: "HSK3",
    wordType: "adverb",
  },
  {
    chinese: "菜单",
    pinyin: "càidān",
    vietnamese: "thực đơn",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "草",
    pinyin: "cǎo",
    vietnamese: "cỏ",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "层",
    pinyin: "céng",
    vietnamese: "tầng",
    level: "HSK3",
    wordType: "measure",
  },
  {
    chinese: "差",
    pinyin: "chà",
    vietnamese: "tệ / kém",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "长城",
    pinyin: "chángchéng",
    vietnamese: "Vạn Lý Trường Thành",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "长江",
    pinyin: "chángjiāng",
    vietnamese: "Sông Trường Giang",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "超市",
    pinyin: "chāoshì",
    vietnamese: "siêu thị",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "衬衫",
    pinyin: "chènshān",
    vietnamese: "áo sơ mi",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "城市",
    pinyin: "chéngshì",
    vietnamese: "thành phố",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "迟到",
    pinyin: "chídào",
    vietnamese: "đến muộn",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "除了",
    pinyin: "chúle",
    vietnamese: "ngoài ra",
    level: "HSK3",
    wordType: "preposition",
  },
  {
    chinese: "春",
    pinyin: "chūn",
    vietnamese: "mùa xuân",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "词语",
    pinyin: "cíyǔ",
    vietnamese: "từ ngữ",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "聪明",
    pinyin: "cōngming",
    vietnamese: "thông minh",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "打扫",
    pinyin: "dǎsǎo",
    vietnamese: "quét dọn",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "打算",
    pinyin: "dǎsuàn",
    vietnamese: "dự định",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "带",
    pinyin: "dài",
    vietnamese: "mang, đem",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "担心",
    pinyin: "dānxīn",
    vietnamese: "lo lắng",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "蛋糕",
    pinyin: "dàngāo",
    vietnamese: "bánh kem",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "当然",
    pinyin: "dāngrán",
    vietnamese: "đương nhiên",
    level: "HSK3",
    wordType: "adverb",
  },
  {
    chinese: "灯",
    pinyin: "dēng",
    vietnamese: "đèn",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "低",
    pinyin: "dī",
    vietnamese: "thấp",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "地方",
    pinyin: "dìfang",
    vietnamese: "địa phương / chỗ",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "地铁",
    pinyin: "dìtiě",
    vietnamese: "tàu điện ngầm",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "地图",
    pinyin: "dìtú",
    vietnamese: "bản đồ",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "电梯",
    pinyin: "diàntī",
    vietnamese: "thang máy",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "东",
    pinyin: "dōng",
    vietnamese: "phía đông",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "冬",
    pinyin: "dōng",
    vietnamese: "mùa đông",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "动物",
    pinyin: "dòngwù",
    vietnamese: "động vật",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "短",
    pinyin: "duǎn",
    vietnamese: "ngắn",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "段",
    pinyin: "duàn",
    vietnamese: "đoạn",
    level: "HSK3",
    wordType: "measure",
  },
  {
    chinese: "锻炼",
    pinyin: "duànliàn",
    vietnamese: "tập luyện",
    level: "HSK3",
    wordType: "verb",
  },
  // ---------- HSK 3 (tiếp theo) ----------
  {
    chinese: "耳朵",
    pinyin: "ěrduo",
    vietnamese: "tai",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "发",
    pinyin: "fā",
    vietnamese: "gửi, phát",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "发现",
    pinyin: "fāxiàn",
    vietnamese: "phát hiện",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "方便",
    pinyin: "fāngbiàn",
    vietnamese: "thuận tiện",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "放",
    pinyin: "fàng",
    vietnamese: "đặt, để",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "放心",
    pinyin: "fàngxīn",
    vietnamese: "yên tâm",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "分",
    pinyin: "fēn",
    vietnamese: "phút / chia",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "复习",
    pinyin: "fùxí",
    vietnamese: "ôn tập",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "附近",
    pinyin: "fùjìn",
    vietnamese: "gần, lân cận",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "干净",
    pinyin: "gānjìng",
    vietnamese: "sạch sẽ",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "感冒",
    pinyin: "gǎnmào",
    vietnamese: "cảm lạnh",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "感兴趣",
    pinyin: "gǎn xìngqù",
    vietnamese: "có hứng thú",
    level: "HSK3",
    wordType: "verb",
  },

  {
    chinese: "跟",
    pinyin: "gēn",
    vietnamese: "với / theo",
    level: "HSK3",
    wordType: "preposition",
  },
  {
    chinese: "根据",
    pinyin: "gēnjù",
    vietnamese: "dựa vào",
    level: "HSK3",
    wordType: "preposition",
  },
  {
    chinese: "更",
    pinyin: "gèng",
    vietnamese: "hơn nữa",
    level: "HSK3",
    wordType: "adverb",
  },
  {
    chinese: "公共汽车",
    pinyin: "gōnggòng qìchē",
    vietnamese: "xe buýt",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "公园",
    pinyin: "gōngyuán",
    vietnamese: "công viên",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "故事",
    pinyin: "gùshi",
    vietnamese: "câu chuyện",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "刮风",
    pinyin: "guāfēng",
    vietnamese: "gió thổi",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "关",
    pinyin: "guān",
    vietnamese: "tắt / đóng",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "关系",
    pinyin: "guānxì",
    vietnamese: "quan hệ",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "关心",
    pinyin: "guānxīn",
    vietnamese: "quan tâm",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "关于",
    pinyin: "guānyú",
    vietnamese: "về việc...",
    level: "HSK3",
    wordType: "preposition",
  },
  {
    chinese: "国家",
    pinyin: "guójiā",
    vietnamese: "quốc gia",
    level: "HSK3",
    wordType: "noun",
  },

  {
    chinese: "过去",
    pinyin: "guòqù",
    vietnamese: "quá khứ",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "还是",
    pinyin: "háishi",
    vietnamese: "hay là",
    level: "HSK3",
    wordType: "conjunction",
  },
  {
    chinese: "害怕",
    pinyin: "hàipà",
    vietnamese: "sợ",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "护照",
    pinyin: "hùzhào",
    vietnamese: "hộ chiếu",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "花",
    pinyin: "huā",
    vietnamese: "hoa / tiêu (tiền)",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "画",
    pinyin: "huà",
    vietnamese: "vẽ",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "坏",
    pinyin: "huài",
    vietnamese: "hỏng, xấu",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "欢迎",
    pinyin: "huānyíng",
    vietnamese: "hoan nghênh",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "环境",
    pinyin: "huánjìng",
    vietnamese: "môi trường",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "换",
    pinyin: "huàn",
    vietnamese: "đổi",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "黄河",
    pinyin: "Huánghé",
    vietnamese: "Hoàng Hà",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "会议",
    pinyin: "huìyì",
    vietnamese: "cuộc họp",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "或者",
    pinyin: "huòzhě",
    vietnamese: "hoặc là",
    level: "HSK3",
    wordType: "conjunction",
  },
  {
    chinese: "几乎",
    pinyin: "jīhū",
    vietnamese: "hầu như",
    level: "HSK3",
    wordType: "adverb",
  },
  {
    chinese: "机会",
    pinyin: "jīhuì",
    vietnamese: "cơ hội",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "极",
    pinyin: "jí",
    vietnamese: "cực kỳ",
    level: "HSK3",
    wordType: "adverb",
  },
  {
    chinese: "记得",
    pinyin: "jìde",
    vietnamese: "nhớ",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "检查",
    pinyin: "jiǎnchá",
    vietnamese: "kiểm tra",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "简单",
    pinyin: "jiǎndān",
    vietnamese: "đơn giản",
    level: "HSK3",
    wordType: "adjective",
  },
  {
    chinese: "见面",
    pinyin: "jiànmiàn",
    vietnamese: "gặp mặt",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "健康",
    pinyin: "jiànkāng",
    vietnamese: "sức khỏe",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "讲",
    pinyin: "jiǎng",
    vietnamese: "nói / giảng",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "脚",
    pinyin: "jiǎo",
    vietnamese: "chân",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "角",
    pinyin: "jiǎo",
    vietnamese: "góc",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "接",
    pinyin: "jiē",
    vietnamese: "đón, nhận",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "街道",
    pinyin: "jiēdào",
    vietnamese: "phố, đường",
    level: "HSK3",
    wordType: "noun",
  },
  {
    chinese: "结婚",
    pinyin: "jiéhūn",
    vietnamese: "kết hôn",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "结束",
    pinyin: "jiéshù",
    vietnamese: "kết thúc",
    level: "HSK3",
    wordType: "verb",
  },
  {
    chinese: "解决",
    pinyin: "jiějué",
    vietnamese: "giải quyết",
    level: "HSK3",
    wordType: "verb",
  },
  // ==========================
  //        HSK 4 — 150 từ
  // ==========================
  {
    chinese: "安排",
    pinyin: "ānpái",
    vietnamese: "sắp xếp",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "安全",
    pinyin: "ānquán",
    vietnamese: "an toàn",
    level: "HSK4",
    wordType: "adjective",
  },
  {
    chinese: "按照",
    pinyin: "ànzhào",
    vietnamese: "dựa theo",
    level: "HSK4",
    wordType: "preposition",
  },
  {
    chinese: "报名",
    pinyin: "bàomíng",
    vietnamese: "đăng ký",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "保护",
    pinyin: "bǎohù",
    vietnamese: "bảo vệ",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "保证",
    pinyin: "bǎozhèng",
    vietnamese: "bảo đảm",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "抱",
    pinyin: "bào",
    vietnamese: "ôm",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "抱歉",
    pinyin: "bàoqiàn",
    vietnamese: "xin lỗi",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "倍",
    pinyin: "bèi",
    vietnamese: "gấp",
    level: "HSK4",
    wordType: "measure",
  },
  {
    chinese: "笨",
    pinyin: "bèn",
    vietnamese: "ngốc",
    level: "HSK4",
    wordType: "adjective",
  },
  {
    chinese: "比如",
    pinyin: "bǐrú",
    vietnamese: "ví dụ",
    level: "HSK4",
    wordType: "conjunction",
  },
  {
    chinese: "毕业",
    pinyin: "bìyè",
    vietnamese: "tốt nghiệp",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "标准",
    pinyin: "biāozhǔn",
    vietnamese: "tiêu chuẩn",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "表示",
    pinyin: "biǎoshì",
    vietnamese: "biểu thị",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "表扬",
    pinyin: "biǎoyáng",
    vietnamese: "khen ngợi",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "并且",
    pinyin: "bìngqiě",
    vietnamese: "hơn nữa",
    level: "HSK4",
    wordType: "conjunction",
  },
  {
    chinese: "不过",
    pinyin: "búguò",
    vietnamese: "nhưng mà",
    level: "HSK4",
    wordType: "conjunction",
  },
  {
    chinese: "不过",
    pinyin: "búguò",
    vietnamese: "chỉ, chỉ có",
    level: "HSK4",
    wordType: "adverb",
  },
  {
    chinese: "部分",
    pinyin: "bùfen",
    vietnamese: "bộ phận",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "擦",
    pinyin: "cā",
    vietnamese: "lau",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "猜",
    pinyin: "cāi",
    vietnamese: "đoán",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "材料",
    pinyin: "cáiliào",
    vietnamese: "tài liệu",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "参观",
    pinyin: "cānguān",
    vietnamese: "tham quan",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "差不多",
    pinyin: "chàbuduō",
    vietnamese: "gần như",
    level: "HSK4",
    wordType: "adverb",
  },
  {
    chinese: "长城",
    pinyin: "Chángchéng",
    vietnamese: "Vạn Lý Trường Thành",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "场",
    pinyin: "chǎng",
    vietnamese: "lượng từ: sân bãi",
    level: "HSK4",
    wordType: "measure",
  },
  {
    chinese: "超过",
    pinyin: "chāoguò",
    vietnamese: "vượt quá",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "成为",
    pinyin: "chéngwéi",
    vietnamese: "trở thành",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "成熟",
    pinyin: "chéngshú",
    vietnamese: "trưởng thành",
    level: "HSK4",
    wordType: "adjective",
  },
  {
    chinese: "重新",
    pinyin: "chóngxīn",
    vietnamese: "làm lại, lại lần nữa",
    level: "HSK4",
    wordType: "adverb",
  },
  {
    chinese: "抽烟",
    pinyin: "chōuyān",
    vietnamese: "hút thuốc",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "出发",
    pinyin: "chūfā",
    vietnamese: "xuất phát",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "出生",
    pinyin: "chūshēng",
    vietnamese: "sinh ra",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "出现",
    pinyin: "chūxiàn",
    vietnamese: "xuất hiện",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "厨房",
    pinyin: "chúfáng",
    vietnamese: "nhà bếp",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "传真",
    pinyin: "chuánzhēn",
    vietnamese: "fax",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "词语",
    pinyin: "cíyǔ",
    vietnamese: "từ ngữ",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "从来",
    pinyin: "cónglái",
    vietnamese: "từ trước đến nay",
    level: "HSK4",
    wordType: "adverb",
  },
  {
    chinese: "粗心",
    pinyin: "cūxīn",
    vietnamese: "cẩu thả",
    level: "HSK4",
    wordType: "adjective",
  },
  {
    chinese: "答案",
    pinyin: "dá'àn",
    vietnamese: "đáp án",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "打扮",
    pinyin: "dǎban",
    vietnamese: "trang điểm",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "打扰",
    pinyin: "dǎrǎo",
    vietnamese: "làm phiền",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "打印",
    pinyin: "dǎyìn",
    vietnamese: "in",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "打折",
    pinyin: "dǎzhé",
    vietnamese: "giảm giá",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "打招呼",
    pinyin: "dǎzhāohu",
    vietnamese: "chào hỏi",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "大概",
    pinyin: "dàgài",
    vietnamese: "đại khái",
    level: "HSK4",
    wordType: "adverb",
  },
  {
    chinese: "大约",
    pinyin: "dàyuē",
    vietnamese: "khoảng",
    level: "HSK4",
    wordType: "adverb",
  },
  {
    chinese: "代表",
    pinyin: "dàibiǎo",
    vietnamese: "đại biểu",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "代替",
    pinyin: "dàitì",
    vietnamese: "thay thế",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "大使馆",
    pinyin: "dàshǐguǎn",
    vietnamese: "đại sứ quán",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "担心",
    pinyin: "dānxīn",
    vietnamese: "lo lắng",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "当",
    pinyin: "dāng",
    vietnamese: "làm (nghề)",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "当地",
    pinyin: "dāngdì",
    vietnamese: "địa phương",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "当然",
    pinyin: "dāngrán",
    vietnamese: "tất nhiên",
    level: "HSK4",
    wordType: "adverb",
  },
  {
    chinese: "刀",
    pinyin: "dāo",
    vietnamese: "dao",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "倒",
    pinyin: "dào",
    vietnamese: "đổ, ngã",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "到处",
    pinyin: "dàochù",
    vietnamese: "khắp nơi",
    level: "HSK4",
    wordType: "adverb",
  },
  {
    chinese: "道歉",
    pinyin: "dàoqiàn",
    vietnamese: "xin lỗi",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "得意",
    pinyin: "déyì",
    vietnamese: "đắc ý",
    level: "HSK4",
    wordType: "adjective",
  },
  {
    chinese: "登机牌",
    pinyin: "dēngjīpái",
    vietnamese: "thẻ lên máy bay",
    level: "HSK4",
    wordType: "noun",
  },

  {
    chinese: "底下",
    pinyin: "dǐxia",
    vietnamese: "phía dưới",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "地点",
    pinyin: "dìdiǎn",
    vietnamese: "địa điểm",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "地球",
    pinyin: "dìqiú",
    vietnamese: "trái đất",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "地址",
    pinyin: "dìzhǐ",
    vietnamese: "địa chỉ",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "调查",
    pinyin: "diàochá",
    vietnamese: "điều tra",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "动作",
    pinyin: "dòngzuò",
    vietnamese: "động tác",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "堵车",
    pinyin: "dǔchē",
    vietnamese: "kẹt xe",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "肚子",
    pinyin: "dùzi",
    vietnamese: "bụng",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "段",
    pinyin: "duàn",
    vietnamese: "đoạn",
    level: "HSK4",
    wordType: "measure",
  },
  {
    chinese: "对话",
    pinyin: "duìhuà",
    vietnamese: "đối thoại",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "对面",
    pinyin: "duìmiàn",
    vietnamese: "đối diện",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "吨",
    pinyin: "dūn",
    vietnamese: "tấn (đơn vị)",
    level: "HSK4",
    wordType: "measure",
  },
  {
    chinese: "发达",
    pinyin: "fādá",
    vietnamese: "phát triển",
    level: "HSK4",
    wordType: "adjective",
  },
  {
    chinese: "发展",
    pinyin: "fāzhǎn",
    vietnamese: "phát triển",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "法律",
    pinyin: "fǎlǜ",
    vietnamese: "pháp luật",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "翻译",
    pinyin: "fānyì",
    vietnamese: "phiên dịch",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "烦恼",
    pinyin: "fánnǎo",
    vietnamese: "phiền não",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "反对",
    pinyin: "fǎnduì",
    vietnamese: "phản đối",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "方法",
    pinyin: "fāngfǎ",
    vietnamese: "phương pháp",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "方面",
    pinyin: "fāngmiàn",
    vietnamese: "phương diện",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "方向",
    pinyin: "fāngxiàng",
    vietnamese: "phương hướng",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "房东",
    pinyin: "fángdōng",
    vietnamese: "chủ nhà",
    level: "HSK4",
    wordType: "noun",
  },
  {
    chinese: "放弃",
    pinyin: "fàngqì",
    vietnamese: "từ bỏ",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "否则",
    pinyin: "fǒuzé",
    vietnamese: "nếu không thì",
    level: "HSK4",
    wordType: "conjunction",
  },
  {
    chinese: "符合",
    pinyin: "fúhé",
    vietnamese: "phù hợp",
    level: "HSK4",
    wordType: "verb",
  },
  {
    chinese: "富",
    pinyin: "fù",
    vietnamese: "giàu",
    level: "HSK4",
    wordType: "adjective",
  },

  {
    chinese: "爱护",
    pinyin: "àihù",
    vietnamese: "yêu quý, trân trọng",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "安装",
    pinyin: "ānzhuāng",
    vietnamese: "lắp đặt",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "把握",
    pinyin: "bǎwò",
    vietnamese: "nắm bắt",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "摆",
    pinyin: "bǎi",
    vietnamese: "bày biện",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "办理",
    pinyin: "bànlǐ",
    vietnamese: "xử lý, làm thủ tục",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "保存",
    pinyin: "bǎocún",
    vietnamese: "bảo tồn, lưu giữ",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "保持",
    pinyin: "bǎochí",
    vietnamese: "duy trì",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "保留",
    pinyin: "bǎoliú",
    vietnamese: "giữ lại",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "报告",
    pinyin: "bàogào",
    vietnamese: "báo cáo",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "编辑",
    pinyin: "biānjí",
    vietnamese: "biên tập",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "表明",
    pinyin: "biǎomíng",
    vietnamese: "chỉ rõ, chứng minh",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "表现",
    pinyin: "biǎoxiàn",
    vietnamese: "thể hiện",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "不安",
    pinyin: "bù'ān",
    vietnamese: "bất an",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "不足",
    pinyin: "bùzú",
    vietnamese: "không đủ",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "操作",
    pinyin: "cāozuò",
    vietnamese: "thao tác",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "测验",
    pinyin: "cèyàn",
    vietnamese: "kiểm tra",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "差别",
    pinyin: "chābié",
    vietnamese: "khác biệt",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "抄",
    pinyin: "chāo",
    vietnamese: "chép",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "炒",
    pinyin: "chǎo",
    vietnamese: "xào,炒菜",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "承担",
    pinyin: "chéngdān",
    vietnamese: "gánh vác",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "成就",
    pinyin: "chéngjiù",
    vietnamese: "thành tựu",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "成语",
    pinyin: "chéngyǔ",
    vietnamese: "thành ngữ",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "承担",
    pinyin: "chéngdān",
    vietnamese: "chịu trách nhiệm",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "促进",
    pinyin: "cùjìn",
    vietnamese: "thúc đẩy",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "促使",
    pinyin: "cùshǐ",
    vietnamese: "khiến cho",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "达到",
    pinyin: "dádào",
    vietnamese: "đạt được",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "扩大",
    pinyin: "kuòdà",
    vietnamese: "mở rộng",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "打听",
    pinyin: "dǎting",
    vietnamese: "hỏi thăm",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "贷款",
    pinyin: "dàikuǎn",
    vietnamese: "vay tiền",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "担任",
    pinyin: "dānrèn",
    vietnamese: "đảm nhiệm",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "登陆",
    pinyin: "dēnglù",
    vietnamese: "đăng nhập",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "登记",
    pinyin: "dēngjì",
    vietnamese: "đăng ký",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "冻结",
    pinyin: "dòngjié",
    vietnamese: "đóng băng",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "独立",
    pinyin: "dúlì",
    vietnamese: "độc lập",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "对象",
    pinyin: "duìxiàng",
    vietnamese: "đối tượng",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "发愁",
    pinyin: "fāchóu",
    vietnamese: "lo lắng",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "发达",
    pinyin: "fādá",
    vietnamese: "phát triển",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "发抖",
    pinyin: "fādǒu",
    vietnamese: "run rẩy",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "发挥",
    pinyin: "fāhuī",
    vietnamese: "phát huy",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "发明",
    pinyin: "fāmíng",
    vietnamese: "phát minh",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "发言",
    pinyin: "fāyán",
    vietnamese: "phát biểu",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "反应",
    pinyin: "fǎnyìng",
    vietnamese: "phản ứng",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "仿佛",
    pinyin: "fǎngfú",
    vietnamese: "hình như",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "放松",
    pinyin: "fàngsōng",
    vietnamese: "thả lỏng",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "分布",
    pinyin: "fēnbù",
    vietnamese: "phân bố",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "分配",
    pinyin: "fēnpèi",
    vietnamese: "phân phối",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "奋斗",
    pinyin: "fèndòu",
    vietnamese: "phấn đấu",
    level: "HSK5",
    wordType: "verb",
  },
  {
    chinese: "风俗",
    pinyin: "fēngsú",
    vietnamese: "phong tục",
    level: "HSK5",
    wordType: "noun",
  },

  {
    chinese: "巨大",
    pinyin: "jùdà",
    vietnamese: "to lớn",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "具备",
    pinyin: "jùbèi",
    vietnamese: "có đủ",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "可靠",
    pinyin: "kěkào",
    vietnamese: "đáng tin",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "可怕",
    pinyin: "kěpà",
    vietnamese: "đáng sợ",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "肯定",
    pinyin: "kěndìng",
    vietnamese: "chắc chắn",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "空闲",
    pinyin: "kòngxián",
    vietnamese: "rảnh rỗi",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "宽",
    pinyin: "kuān",
    vietnamese: "rộng",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "明确",
    pinyin: "míngquè",
    vietnamese: "rõ ràng",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "难免",
    pinyin: "nánmiǎn",
    vietnamese: "khó tránh",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "疏忽",
    pinyin: "shūhu",
    vietnamese: "lơ là",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "顽固",
    pinyin: "wángù",
    vietnamese: "ngoan cố",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "稳定",
    pinyin: "wěndìng",
    vietnamese: "ổn định",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "鲜艳",
    pinyin: "xiānyàn",
    vietnamese: "rực rỡ",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "虚心",
    pinyin: "xūxīn",
    vietnamese: "khiêm tốn",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "遥远",
    pinyin: "yáoyuǎn",
    vietnamese: "xa xôi",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "一般",
    pinyin: "yībān",
    vietnamese: "bình thường",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "义务",
    pinyin: "yìwù",
    vietnamese: "nghĩa vụ",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "友好",
    pinyin: "yǒuhǎo",
    vietnamese: "thân thiện",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "优秀",
    pinyin: "yōuxiù",
    vietnamese: "xuất sắc",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "悠久",
    pinyin: "yōujiǔ",
    vietnamese: "lâu đời",
    level: "HSK5",
    wordType: "adjective",
  },
  {
    chinese: "爱心",
    pinyin: "àixīn",
    vietnamese: "lòng nhân ái",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "安装",
    pinyin: "ānzhuāng",
    vietnamese: "việc lắp đặt",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "把握",
    pinyin: "bǎwò",
    vietnamese: "sự nắm bắt",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "背景",
    pinyin: "bèijǐng",
    vietnamese: "bối cảnh",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "本质",
    pinyin: "běnzhì",
    vietnamese: "bản chất",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "比例",
    pinyin: "bǐlì",
    vietnamese: "tỷ lệ",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "步骤",
    pinyin: "bùzhòu",
    vietnamese: "bước, quy trình",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "财产",
    pinyin: "cáichǎn",
    vietnamese: "tài sản",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "产品",
    pinyin: "chǎnpǐn",
    vietnamese: "sản phẩm",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "成果",
    pinyin: "chéngguǒ",
    vietnamese: "thành quả",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "成人",
    pinyin: "chéngrén",
    vietnamese: "người lớn",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "处理",
    pinyin: "chǔlǐ",
    vietnamese: "xử lý",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "传统",
    pinyin: "chuántǒng",
    vietnamese: "truyền thống",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "对象",
    pinyin: "duìxiàng",
    vietnamese: "đối tượng",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "范围",
    pinyin: "fànwéi",
    vietnamese: "phạm vi",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "方案",
    pinyin: "fāng'àn",
    vietnamese: "phương án",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "风格",
    pinyin: "fēnggé",
    vietnamese: "phong cách",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "角色",
    pinyin: "juésè",
    vietnamese: "vai trò",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "结构",
    pinyin: "jiégòu",
    vietnamese: "kết cấu",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "技巧",
    pinyin: "jìqiǎo",
    vietnamese: "kỹ xảo",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "记忆",
    pinyin: "jìyì",
    vietnamese: "trí nhớ",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "记录",
    pinyin: "jìlù",
    vietnamese: "ghi chép",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "课程",
    pinyin: "kèchéng",
    vietnamese: "khóa học",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "逻辑",
    pinyin: "luójí",
    vietnamese: "logic",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "贸易",
    pinyin: "màoyì",
    vietnamese: "thương mại",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "目录",
    pinyin: "mùlù",
    vietnamese: "mục lục",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "难题",
    pinyin: "nántí",
    vietnamese: "vấn đề khó",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "年代",
    pinyin: "niándài",
    vietnamese: "niên đại",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "企业",
    pinyin: "qǐyè",
    vietnamese: "doanh nghiệp",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "缺乏",
    pinyin: "quēfá",
    vietnamese: "thiếu hụt",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "人才",
    pinyin: "réncái",
    vietnamese: "nhân tài",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "日常",
    pinyin: "rìcháng",
    vietnamese: "thường ngày",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "设备",
    pinyin: "shèbèi",
    vietnamese: "thiết bị",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "设施",
    pinyin: "shèshī",
    vietnamese: "cơ sở vật chất",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "事实",
    pinyin: "shìshí",
    vietnamese: "sự thật",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "市场",
    pinyin: "shìchǎng",
    vietnamese: "thị trường",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "试卷",
    pinyin: "shìjuàn",
    vietnamese: "bài thi",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "损失",
    pinyin: "sǔnshī",
    vietnamese: "tổn thất",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "态度",
    pinyin: "tàidu",
    vietnamese: "thái độ",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "特点",
    pinyin: "tèdiǎn",
    vietnamese: "đặc điểm",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "未来",
    pinyin: "wèilái",
    vietnamese: "tương lai",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "现象",
    pinyin: "xiànxiàng",
    vietnamese: "hiện tượng",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "写作",
    pinyin: "xiězuò",
    vietnamese: "viết lách",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "形式",
    pinyin: "xíngshì",
    vietnamese: "hình thức",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "讯息",
    pinyin: "xùnxī",
    vietnamese: "thông tin",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "业务",
    pinyin: "yèwù",
    vietnamese: "nghiệp vụ",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "因素",
    pinyin: "yīnsù",
    vietnamese: "yếu tố",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "英雄",
    pinyin: "yīngxióng",
    vietnamese: "anh hùng",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "应用",
    pinyin: "yìngyòng",
    vietnamese: "ứng dụng",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "永久",
    pinyin: "yǒngjiǔ",
    vietnamese: "lâu dài",
    level: "HSK5",
    wordType: "noun",
  },
  {
    chinese: "预报",
    pinyin: "yùbào",
    vietnamese: "dự báo",
    level: "HSK5",
    wordType: "noun",
  },
];

async function getSystemUserId() {
  let system = await User.findOne({ email: "system@panda.edu" });

  if (!system) {
    console.log("⚠️  System user not found → creating new one...");

    system = await User.create({
      fullName: "System",
      email: "system@panda.edu",
      password: "123456", // Password không dùng đến
      role: "teacher",
    });

    console.log("✔ Created System User:", system._id);
  } else {
    console.log("✔ Found System User:", system._id);
  }

  return system._id;
}

/* ================================
 * 3. SEED FUNCTION CHÍNH
 * ================================ */
async function seed() {
  try {
    console.log("⏳ Connecting to MongoDB...");
    await mongoose.connect(process.env.MONGO_URI);

    const systemUserId = await getSystemUserId();

    console.log("🔥 Preparing payload...");

    // Gán createdBy + isSystem
    const payload = seedData.map((item) => ({
      ...item,
      isSystem: true,
      createdBy: systemUserId,
    }));

    console.log("🔥 Importing vocabulary...");

    await Vocabulary.insertMany(payload);

    console.log(`🎉 DONE! Imported ${payload.length} vocabulary items.`);
    process.exit();
  } catch (err) {
    console.error("❌ Error seeding vocabulary:", err);
    process.exit(1);
  }
}

seed();
